//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConnect.ServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="appleAcount", Namespace="http://schemas.datacontract.org/2004/07/SqlModel")]
    [System.SerializableAttribute()]
    public partial class appleAcount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cancelUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cookiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string daytimePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string daytimePhoneAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginAppleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shippingUserFistNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shippingUserLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shippingUserStreet1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shippingUserStreet2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w1RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w1detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w2RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w2detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w3RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string w3detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cancelUrl {
            get {
                return this.cancelUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.cancelUrlField, value) != true)) {
                    this.cancelUrlField = value;
                    this.RaisePropertyChanged("cancelUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cookies {
            get {
                return this.cookiesField;
            }
            set {
                if ((object.ReferenceEquals(this.cookiesField, value) != true)) {
                    this.cookiesField = value;
                    this.RaisePropertyChanged("cookies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string daytimePhone {
            get {
                return this.daytimePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.daytimePhoneField, value) != true)) {
                    this.daytimePhoneField = value;
                    this.RaisePropertyChanged("daytimePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string daytimePhoneAreaCode {
            get {
                return this.daytimePhoneAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.daytimePhoneAreaCodeField, value) != true)) {
                    this.daytimePhoneAreaCodeField = value;
                    this.RaisePropertyChanged("daytimePhoneAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginAppleId {
            get {
                return this.loginAppleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginAppleIdField, value) != true)) {
                    this.loginAppleIdField = value;
                    this.RaisePropertyChanged("loginAppleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postalCodeField, value) != true)) {
                    this.postalCodeField = value;
                    this.RaisePropertyChanged("postalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                if ((object.ReferenceEquals(this.remarksField, value) != true)) {
                    this.remarksField = value;
                    this.RaisePropertyChanged("remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shippingUserFistName {
            get {
                return this.shippingUserFistNameField;
            }
            set {
                if ((object.ReferenceEquals(this.shippingUserFistNameField, value) != true)) {
                    this.shippingUserFistNameField = value;
                    this.RaisePropertyChanged("shippingUserFistName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shippingUserLastName {
            get {
                return this.shippingUserLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.shippingUserLastNameField, value) != true)) {
                    this.shippingUserLastNameField = value;
                    this.RaisePropertyChanged("shippingUserLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shippingUserStreet1 {
            get {
                return this.shippingUserStreet1Field;
            }
            set {
                if ((object.ReferenceEquals(this.shippingUserStreet1Field, value) != true)) {
                    this.shippingUserStreet1Field = value;
                    this.RaisePropertyChanged("shippingUserStreet1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shippingUserStreet2 {
            get {
                return this.shippingUserStreet2Field;
            }
            set {
                if ((object.ReferenceEquals(this.shippingUserStreet2Field, value) != true)) {
                    this.shippingUserStreet2Field = value;
                    this.RaisePropertyChanged("shippingUserStreet2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w1 {
            get {
                return this.w1Field;
            }
            set {
                if ((object.ReferenceEquals(this.w1Field, value) != true)) {
                    this.w1Field = value;
                    this.RaisePropertyChanged("w1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w1Remark {
            get {
                return this.w1RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.w1RemarkField, value) != true)) {
                    this.w1RemarkField = value;
                    this.RaisePropertyChanged("w1Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w1detail {
            get {
                return this.w1detailField;
            }
            set {
                if ((object.ReferenceEquals(this.w1detailField, value) != true)) {
                    this.w1detailField = value;
                    this.RaisePropertyChanged("w1detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w2 {
            get {
                return this.w2Field;
            }
            set {
                if ((object.ReferenceEquals(this.w2Field, value) != true)) {
                    this.w2Field = value;
                    this.RaisePropertyChanged("w2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w2Remark {
            get {
                return this.w2RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.w2RemarkField, value) != true)) {
                    this.w2RemarkField = value;
                    this.RaisePropertyChanged("w2Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w2detail {
            get {
                return this.w2detailField;
            }
            set {
                if ((object.ReferenceEquals(this.w2detailField, value) != true)) {
                    this.w2detailField = value;
                    this.RaisePropertyChanged("w2detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w3 {
            get {
                return this.w3Field;
            }
            set {
                if ((object.ReferenceEquals(this.w3Field, value) != true)) {
                    this.w3Field = value;
                    this.RaisePropertyChanged("w3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w3Remark {
            get {
                return this.w3RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.w3RemarkField, value) != true)) {
                    this.w3RemarkField = value;
                    this.RaisePropertyChanged("w3Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string w3detail {
            get {
                return this.w3detailField;
            }
            set {
                if ((object.ReferenceEquals(this.w3detailField, value) != true)) {
                    this.w3detailField = value;
                    this.RaisePropertyChanged("w3detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string wCount {
            get {
                return this.wCountField;
            }
            set {
                if ((object.ReferenceEquals(this.wCountField, value) != true)) {
                    this.wCountField = value;
                    this.RaisePropertyChanged("wCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClient.IServiceContract")]
    public interface IServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetDateTime", ReplyAction="http://tempuri.org/IServiceContract/GetDateTimeResponse")]
        System.DateTime GetDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetDateTime", ReplyAction="http://tempuri.org/IServiceContract/GetDateTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetDateTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetAllUserInfos", ReplyAction="http://tempuri.org/IServiceContract/GetAllUserInfosResponse")]
        WCFConnect.ServiceClient.appleAcount[] GetAllUserInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetAllUserInfos", ReplyAction="http://tempuri.org/IServiceContract/GetAllUserInfosResponse")]
        System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount[]> GetAllUserInfosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetAUserInfo", ReplyAction="http://tempuri.org/IServiceContract/GetAUserInfoResponse")]
        WCFConnect.ServiceClient.appleAcount GetAUserInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetAUserInfo", ReplyAction="http://tempuri.org/IServiceContract/GetAUserInfoResponse")]
        System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount> GetAUserInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/Login", ReplyAction="http://tempuri.org/IServiceContract/LoginResponse")]
        WCFConnect.ServiceClient.appleAcount Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/Login", ReplyAction="http://tempuri.org/IServiceContract/LoginResponse")]
        System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount> LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/ParallelTest", ReplyAction="http://tempuri.org/IServiceContract/ParallelTestResponse")]
        WCFConnect.ServiceClient.appleAcount ParallelTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/ParallelTest", ReplyAction="http://tempuri.org/IServiceContract/ParallelTestResponse")]
        System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount> ParallelTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/DeleteUserInfo", ReplyAction="http://tempuri.org/IServiceContract/DeleteUserInfoResponse")]
        bool DeleteUserInfo(WCFConnect.ServiceClient.appleAcount userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/DeleteUserInfo", ReplyAction="http://tempuri.org/IServiceContract/DeleteUserInfoResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserInfoAsync(WCFConnect.ServiceClient.appleAcount userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/EditUserInfo", ReplyAction="http://tempuri.org/IServiceContract/EditUserInfoResponse")]
        int EditUserInfo(WCFConnect.ServiceClient.appleAcount userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/EditUserInfo", ReplyAction="http://tempuri.org/IServiceContract/EditUserInfoResponse")]
        System.Threading.Tasks.Task<int> EditUserInfoAsync(WCFConnect.ServiceClient.appleAcount userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/AddUserInfo", ReplyAction="http://tempuri.org/IServiceContract/AddUserInfoResponse")]
        bool AddUserInfo(WCFConnect.ServiceClient.appleAcount userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/AddUserInfo", ReplyAction="http://tempuri.org/IServiceContract/AddUserInfoResponse")]
        System.Threading.Tasks.Task<bool> AddUserInfoAsync(WCFConnect.ServiceClient.appleAcount userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetOrder", ReplyAction="http://tempuri.org/IServiceContract/GetOrderResponse")]
        string GetOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContract/GetOrder", ReplyAction="http://tempuri.org/IServiceContract/GetOrderResponse")]
        System.Threading.Tasks.Task<string> GetOrderAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceContractChannel : WCFConnect.ServiceClient.IServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceContractClient : System.ServiceModel.ClientBase<WCFConnect.ServiceClient.IServiceContract>, WCFConnect.ServiceClient.IServiceContract {
        
        public ServiceContractClient() {
        }
        
        public ServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetDateTime() {
            return base.Channel.GetDateTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDateTimeAsync() {
            return base.Channel.GetDateTimeAsync();
        }
        
        public WCFConnect.ServiceClient.appleAcount[] GetAllUserInfos() {
            return base.Channel.GetAllUserInfos();
        }
        
        public System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount[]> GetAllUserInfosAsync() {
            return base.Channel.GetAllUserInfosAsync();
        }
        
        public WCFConnect.ServiceClient.appleAcount GetAUserInfo(int id) {
            return base.Channel.GetAUserInfo(id);
        }
        
        public System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount> GetAUserInfoAsync(int id) {
            return base.Channel.GetAUserInfoAsync(id);
        }
        
        public WCFConnect.ServiceClient.appleAcount Login() {
            return base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount> LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public WCFConnect.ServiceClient.appleAcount ParallelTest() {
            return base.Channel.ParallelTest();
        }
        
        public System.Threading.Tasks.Task<WCFConnect.ServiceClient.appleAcount> ParallelTestAsync() {
            return base.Channel.ParallelTestAsync();
        }
        
        public bool DeleteUserInfo(WCFConnect.ServiceClient.appleAcount userInfo) {
            return base.Channel.DeleteUserInfo(userInfo);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserInfoAsync(WCFConnect.ServiceClient.appleAcount userInfo) {
            return base.Channel.DeleteUserInfoAsync(userInfo);
        }
        
        public int EditUserInfo(WCFConnect.ServiceClient.appleAcount userInfo) {
            return base.Channel.EditUserInfo(userInfo);
        }
        
        public System.Threading.Tasks.Task<int> EditUserInfoAsync(WCFConnect.ServiceClient.appleAcount userInfo) {
            return base.Channel.EditUserInfoAsync(userInfo);
        }
        
        public bool AddUserInfo(WCFConnect.ServiceClient.appleAcount userInfo) {
            return base.Channel.AddUserInfo(userInfo);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserInfoAsync(WCFConnect.ServiceClient.appleAcount userInfo) {
            return base.Channel.AddUserInfoAsync(userInfo);
        }
        
        public string GetOrder() {
            return base.Channel.GetOrder();
        }
        
        public System.Threading.Tasks.Task<string> GetOrderAsync() {
            return base.Channel.GetOrderAsync();
        }
    }
}
